# Generated by Django 4.1.3 on 2023-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_data',
            name='id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students_data',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
