# Generated by Django 4.1.3 on 2023-05-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students_Data',
        ),
    ]
