# Generated by Django 4.1.3 on 2023-05-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_delete_students_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Data',
            fields=[
                ('id', models.IntegerField(unique=True)),
                ('NIM', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.major_data')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.status_data')),
            ],
        ),
    ]
