# Generated by Django 4.1.3 on 2023-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_data',
            name='id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
