# Generated by Django 4.1.3 on 2023-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_students_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_data',
            name='NIM',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
