# Generated by Django 4.1.3 on 2023-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_students_data_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_data',
            name='contact',
            field=models.IntegerField(max_length=20),
        ),
    ]
