# Generated by Django 4.1.3 on 2023-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_students_data_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_data',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
